blog_app/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria')
]

carro_app/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [

    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

proyecto_web/urls.py
import carro_app
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proyecto_web_app.urls')),
    path('servicios/', include('servicios_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('contacto/', include('contacto_app.urls')),
    path('tienda/', include('tienda_app.urls')),
    path('carro/', include('carro_app.urls')),
    path('autenticacion/', include('autenticacion.urls')),
]

tienda_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tienda, name='tienda'),
]

tienda_app/models.py
from django.db import models



# Create your models here.

class CategoriaProd(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categororiaProd'
        verbose_name_plural = 'categoriasProd'

    def __str__(self) -> str:
        return self.name

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'porducto'
        verbose_name_plural = 'productos'

    def __str__(self) -> str:
        return self.nombre
        

tienda_app/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.


def tienda(request):

    productos = Producto.objects.all()

    
    return render(request, 'tienda_app/tienda.html',{
        'productos':productos
    })

tienda_app/templates/carro/widget.html
<table class="table table-bordered" style="color:aliceblue;">
    <thead>

        <tr>

            <th colspan="3" class="text-center">
                Carro compras
            </th>

        </tr>

        <tr class="text-center">

            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        

        </tr>

    </thead>

    <tbody>

        {% if request.session.carro.items %}

            {% for key, value in request.session.carro.items %}

                <tr class="text-center">
                    <th>{{value.nombre}}</th>
                    <th>{{value.cantidad}}</th>
                    <th>


                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                        <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-success" style="float: right;">x</a><br>
                        $ {{value.precio}} COP
                    </th>

                </tr>

            {% endfor %}

        {% else %}

            <tr>
                <th colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </th>
            </tr>


        {% endif %}



    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: {{importe_total_carro}}
                <a href="{% url 'carro:limpiar'%}" class="btn btn-sm btn-success" style="float: right;">limpiar</a>
            </td>
        </tr>
    </tfoot>

</table>